### ISSUE TITLE
Can't resolve components on latest geppetto-meta version

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#275] opened 2022-02-03 18:48 UTC
**Steps to reproduce:**

1. `git clone -b geppetto/bug https://github.com/MetaCell/salk-interactive-atlas.git`
2. `cd salk-interactive-atlas/applications/salk-portal`
3. `npm i`
4. `npm run build`

**Expected** (which is what happens on branch [feature/poc](https://github.com/MetaCell/salk-interactive-atlas/tree/feature/poc) that uses geppetto-meta version 0.0.8):
 ```
 > portal@0.0.1 prebuild /home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal
> tslint -c tslint.json 'src/**/*.{ts,tsx}'


> portal@0.0.1 build /home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal
> webpack --mode=production --config webpack.prod.js --devtool source-map

Contentbase: /home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal/public
```

**Actual result:**

```
ERROR in ./src/App.tsx 30:0-65
Module not found: Error: Can't resolve '@metacell/geppetto-meta-ui/flex-layout/style/dark.scss' in '/home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal/src'
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

ERROR in ./src/App.tsx 36:16-80
Module not found: Error: Can't resolve '@metacell/geppetto-meta-client/common/Manager' in '/home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal/src'
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

ERROR in ./src/App.tsx 42:21-78
Module not found: Error: Can't resolve '@metacell/geppetto-meta-core/Resources' in '/home/afonso/Projects/MetaCell/salk-interactive-atlas/applications/salk-portal/src'
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

...

```

**Comment by enicolasgomez** [comment] 2022-02-17 13:17
@afonsobspinto this should be fixed by using 1.0.0-rc6 - I will also release a new redux sample app as while working on this noticed that the boiler plate is way to complex for a new commer to geppetto-meta

**Comment by enicolasgomez** [comment] 2022-02-21 16:08
it will only fail for released versions, if run from yalc it will succeed:

```
    "@metacell/geppetto-meta-client": "file:.yalc/@metacell/geppetto-meta-client",
    "@metacell/geppetto-meta-core": "file:.yalc/@metacell/geppetto-meta-core",
    "@metacell/geppetto-meta-ui": "file:.yalc/@metacell/geppetto-meta-ui",
```

**Comment by enicolasgomez** [comment] 2022-02-21 16:11
the only noticeable difference is that in node_modules, any of the three packages include node_modules folder for the yalc file version, the release version does not include it

**Comment by filippomc** [comment] 2022-02-21 17:12
Tried with 1.0.0-rc6 the issue is still present.

I could do some progress by removing that strange exports from https://github.com/MetaCell/geppetto-meta/blob/6d2d5af18f0ef25bb6ff7b4389dd3f5bb6fd8978/geppetto.js/geppetto-core/package.json#L45 https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/package.json#L129

```
yarn run v1.22.5
$ tslint -c tslint.json 'src/**/*.{ts,tsx}'
$ webpack --mode=production --config webpack.prod.js --devtool source-map
Contentbase: /home/user/salk-interactive-atlas/applications/salk-portal/public
ERROR in ./node_modules/@metacell/geppetto-meta-ui/camera-controls/CameraControls.js 32:25-69
Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/camera-controls'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 36:22-66
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/capture-controls/CaptureControls.js 30:25-69
Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/capture-controls'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 46:23-69
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/common/IconButtonWithTooltip.js 16:24-65
Module not found: Error: Can't resolve '@fortawesome/react-fontawesome' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/common'
 @ ./node_modules/@metacell/geppetto-meta-ui/camera-controls/CameraControls.js 28:52-94
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 36:22-66
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 40:50-82
Module not found: Error: Can't resolve 'react-resize-detector' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas'
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/captureManager/Screenshoter.js 24:42-66
Module not found: Error: Can't resolve 'html-to-image' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/captureManager'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 44:20-60
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/MeshFactory.js 16:18-66
Module not found: Error: Can't resolve 'three/examples/jsm/loaders/GLTFLoader' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 42:42-66
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/MeshFactory.js 20:19-68
Module not found: Error: Can't resolve 'three/examples/jsm/loaders/DRACOLoader' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 42:42-66
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/MeshFactory.js 22:21-72
Module not found: Error: Can't resolve 'three/examples/jsm/loaders/ColladaLoader' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 42:42-66
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 30:18-76
Module not found: Error: Can't resolve 'three/examples/jsm/postprocessing/RenderPass.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 32:22-84
Module not found: Error: Can't resolve 'three/examples/jsm/postprocessing/EffectComposer.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 34:18-76
Module not found: Error: Can't resolve 'three/examples/jsm/postprocessing/ShaderPass.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 36:17-74
Module not found: Error: Can't resolve 'three/examples/jsm/postprocessing/BloomPass.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 38:16-72
Module not found: Error: Can't resolve 'three/examples/jsm/postprocessing/FilmPass.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine/ThreeDEngine.js 40:19-71
Module not found: Error: Can't resolve 'three/examples/jsm/shaders/FocusShader.js' in '/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/@metacell/geppetto-meta-ui/3d-canvas/threeDEngine'
 @ ./node_modules/@metacell/geppetto-meta-ui/3d-canvas/Canvas.js 34:43-81
 @ ./src/components/CanvasExample.tsx 28:33-87
 @ ./src/components/layout/componentMap.tsx 7:40-67
 @ ./src/store/configureStore.ts 10:39-83
 @ ./src/store/store.ts 6:41-68
 @ ./src/index.tsx 28:32-56

ERROR in ./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/sass-loader/dist/utils.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/sass-loader/dist/index.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/sass-loader/dist/cjs.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/loader-runner/lib/loadLoader.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/loader-runner/lib/LoaderRunner.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack/lib/NormalModuleFactory.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack/lib/Compiler.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack/lib/webpack.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack/lib/index.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack-cli/lib/webpack-cli.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack-cli/lib/bootstrap.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack-cli/bin/cli.js
- /home/user/salk-interactive-atlas/applications/salk-portal/node_modules/webpack/bin/webpack.js
 @ ./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss 2:26-121
 @ ./src/App.tsx 30:0-65
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

ERROR in ./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/postcss/lib/input.js:24:13)
    at parse (/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/home/user/salk-interactive-atlas/applications/salk-portal/node_modules/css-loader/dist/index.js:140:51)
 @ ./node_modules/@metacell/geppetto-meta-ui/flex-layout/style/dark.scss 2:26-121
 @ ./src/App.tsx 30:0-65
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

ERROR in ./src/App.tsx 36:16-80
Module not found: Error: Can't resolve '@metacell/geppetto-meta-client/common/Manager' in '/home/user/salk-interactive-atlas/applications/salk-portal/src'
 @ ./src/components/index.ts 5:14-31
 @ ./src/index.tsx 27:16-45

webpack compiled with 17 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also strange that the node_modules folder is included inside geppetto-meta-client, but that does not seem to have influence.

As for the Salk project, it needs other some tweaks to build correctly after the above trick:
- add explicitly the dependencies as they have been moved as peer dependencies. Can either copy all peer dependencies from the geppetto-client and geppetto-ui to the salk dependencies or do some trial and error by adding only the ones that are actually needed (e.g. three is needed, probably ami not). As a rule of thumb, usually all geppetto-client dependencies are needed, only a part of geppetto-ui are.
- Add a loader for less files
- @metacell/geppetto-meta-client/common/Manager -> @metacell/geppetto-meta-client/common/GeppettoManager

**Comment by enicolasgomez** [comment] 2022-02-24 12:48
Fixed on Rc8

**Comment by afonsobspinto** [comment] 2022-02-28 15:02
imo can be closed cc @enicolasgomez

**Closed** 2022-03-22 16:51 UTC
Labels: bug, geppetto.js
