### ISSUE TITLE
Propagate panel actions to widgets on LayoutManager

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#349] opened 2022-03-24 14:44 UTC
There's this bug in salk where when we maximize the panel, the canvas doesn't get updated.
@ddelpiano showed me that the problem seems to be that when we do the maximize we are updating the panel and not the widgets.
We need a proper way to pass this information to the widgets.

Entry point of where we need to trigger the update seems to be [here](https://github.com/MetaCell/geppetto-meta/blob/development/geppetto.js/geppetto-client/src/common/layout/LayoutManager.tsx#L392)

**Comment by filippomc** [comment] 2022-03-24 14:47
Seems to be a duplicate of https://github.com/MetaCell/geppetto-meta/issues/108

**Closed** 2022-04-05 16:33 UTC
Labels: bug, geppetto-client, high priority
